language: go
go:
 - 1.7.x
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.x
 - 1.12.x
 - 1.13.x
 - 1.14.x
 - tip
gobuild_args: -tags no_pkg_config
dist: xenial
addons:
  apt:
    packages:
    - bison
    - flex
    - automake
    - autoconf
    - libtool
    - make
    - gcc
before_install:
  - wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v3.11.0.tar.gz | tar -C ${TRAVIS_BUILD_DIR} -xzf -
  - ( cd ${TRAVIS_BUILD_DIR}/yara-3.11.0 && ./bootstrap.sh && ./configure && make )
  - export CGO_CFLAGS=-I${TRAVIS_BUILD_DIR}/yara-3.11.0/libyara/include
  - export CGO_LDFLAGS=-L${TRAVIS_BUILD_DIR}/yara-3.11.0/libyara/.libs
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/yara-3.11.0/libyara/.libs
